apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todoapp
        image: pritamcalsoft/todoapp:v1
        ports:
        - containerPort: 8081

